spring.application.name=sb4-sla-validation-test
spring.threads.virtual.enabled=true
downstream.a.url=http://localhost:18081/a
downstream.b.url=http://localhost:18082/b
downstream.c.url=http://localhost:18083/c
