package com.macstab.chaos.jvm.instrumentation;

import static org.assertj.core.api.Assertions.assertThat;

import com.macstab.chaos.jvm.instrumentation.bridge.BootstrapDispatcher;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

@DisplayName("QueueAdvice")
class QueueAdviceTest {

  private final Object queue = new Object();

  @AfterEach
  void resetBridge() {
    BootstrapDispatcher.install(null, null);
  }

  @Nested
  @DisplayName("OfferAdvice enter \u2014 skip logic")
  class OfferAdviceEnterSkipLogic {

    @Test
    @DisplayName("returns null (no skip) when bridge is not installed")
    void returnsNullWhenBridgeNotInstalled() throws Throwable {
      assertThat(QueueAdvice.OfferAdvice.enter(queue)).isNull();
    }

    @Test
    @DisplayName("returns null (no skip) when bridge returns null")
    void returnsNullWhenBridgeReturnsNull() throws Throwable {
      installBooleanQueueBridge((op, q) -> null);
      assertThat(QueueAdvice.OfferAdvice.enter(queue)).isNull();
    }

    @Test
    @DisplayName("returns TRUE (skip) when bridge returns TRUE \u2014 offer fakes success")
    void returnsTrueWhenBridgeReturnsTrue() throws Throwable {
      // The enter value is what skipOn=OnNonDefaultValue evaluates. Any non-null Boolean
      // means skip the real offer body; exit then substitutes this Boolean as the return
      // value. Previous collapsed contract (TRUE \u2192 no-skip) lost the ability for chaos to
      // report a fake successful offer.
      installBooleanQueueBridge((op, q) -> Boolean.TRUE);
      assertThat(QueueAdvice.OfferAdvice.enter(queue)).isEqualTo(Boolean.TRUE);
    }

    @Test
    @DisplayName("returns FALSE (skip) when bridge returns FALSE \u2014 offer is suppressed")
    void returnsFalseWhenBridgeReturnsFalse() throws Throwable {
      installBooleanQueueBridge((op, q) -> Boolean.FALSE);
      assertThat(QueueAdvice.OfferAdvice.enter(queue)).isEqualTo(Boolean.FALSE);
    }

    @Test
    @DisplayName("passes QUEUE_OFFER operation and queue identity to bridge")
    void passesOperationAndQueueToBridge() throws Throwable {
      final AtomicReference<String> capturedOp = new AtomicReference<>();
      final AtomicReference<Object> capturedQueue = new AtomicReference<>();
      installBooleanQueueBridge(
          (op, q) -> {
            capturedOp.set(op);
            capturedQueue.set(q);
            return null;
          });

      QueueAdvice.OfferAdvice.enter(queue);

      assertThat(capturedOp.get()).isEqualTo("QUEUE_OFFER");
      assertThat(capturedQueue.get()).isSameAs(queue);
    }
  }

  @Nested
  @DisplayName("OfferAdvice exit \u2014 return rewrite")
  class OfferAdviceExitReturnRewrite {

    @Test
    @DisplayName("no rewrite when decision is null (real offer result passes through)")
    void noRewriteWhenDecisionIsNull() {
      final boolean[] returned = {true};
      // Exit rewrites "returned" in-place only when decision != null; the real offer's outcome
      // (true or false) is preserved. Simulate by mutating the array since the advice mutates
      // a @Advice.Return local directly in its generated form.
      applyExit(null, returned);
      assertThat(returned[0]).isTrue();
    }

    @Test
    @DisplayName("rewrites to FALSE when decision is FALSE")
    void rewriteWhenDecisionIsFalse() {
      final boolean[] returned = {true};
      applyExit(Boolean.FALSE, returned);
      assertThat(returned[0]).isFalse();
    }

    @Test
    @DisplayName("rewrites to TRUE when decision is TRUE")
    void rewriteWhenDecisionIsTrue() {
      final boolean[] returned = {false};
      applyExit(Boolean.TRUE, returned);
      assertThat(returned[0]).isTrue();
    }

    /**
     * Mirror of the advice exit body. The real advice mutates a {@code @Advice.Return(readOnly =
     * false) boolean returned} local variable generated by ByteBuddy; a unit test cannot invoke
     * that mutation directly so it reproduces the same branch with a single-element array to keep
     * the semantic check close to the advice source.
     */
    private static void applyExit(final Boolean decision, final boolean[] returned) {
      if (decision != null) {
        returned[0] = decision;
      }
    }
  }

  // \u2014 bridge test infrastructure \u2014

  @FunctionalInterface
  interface BooleanQueueBehavior {
    Boolean behave(String operation, Object queue) throws Throwable;
  }

  private static void installBooleanQueueBridge(final BooleanQueueBehavior behavior)
      throws Exception {
    final MethodHandle[] handles = new MethodHandle[BootstrapDispatcher.HANDLE_COUNT];
    handles[BootstrapDispatcher.BEFORE_BOOLEAN_QUEUE_OPERATION] =
        MethodHandles.lookup()
            .findVirtual(
                BooleanQueueBehavior.class,
                "behave",
                MethodType.methodType(Boolean.class, String.class, Object.class));
    BootstrapDispatcher.install(behavior, handles);
  }
}
