package com.macstab.chaos.quarkus;

import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.annotations.ExecutionTime;
import io.quarkus.deployment.annotations.Record;
import io.quarkus.deployment.builditem.FeatureBuildItem;

/**
 * Build-time processor that registers the chaos-agent extension with the Quarkus build graph.
 *
 * <p>Two things happen during the build:
 *
 * <ul>
 *   <li>A {@link FeatureBuildItem} named {@code "macstab-chaos-agent"} is produced so the feature
 *       appears in the Quarkus startup banner.
 *   <li>The {@link ChaosQuarkusRecorder} installs the chaos agent at runtime initialization so it
 *       is ready before any application code executes.
 * </ul>
 */
public final class ChaosQuarkusBuildStep {

  /** Default constructor; Quarkus instantiates build-step classes reflectively. */
  public ChaosQuarkusBuildStep() {}

  /**
   * Emits the feature marker and records the runtime-init call to install the chaos agent.
   *
   * @param recorder the build-time recorder stub; the generated bytecode calls {@link
   *     ChaosQuarkusRecorder#installAgent()} on the live recorder at runtime
   * @return the {@link FeatureBuildItem} so Quarkus registers the feature in its build graph
   */
  @BuildStep
  @Record(ExecutionTime.RUNTIME_INIT)
  public FeatureBuildItem installChaosAgent(final ChaosQuarkusRecorder recorder) {
    recorder.installAgent();
    return new FeatureBuildItem("macstab-chaos-agent");
  }
}
