package com.macstab.chaos.quarkus;

import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.annotations.ExecutionTime;
import io.quarkus.deployment.annotations.Record;
import io.quarkus.deployment.builditem.FeatureBuildItem;

/**
 * Build-time processor that registers the chaos-agent extension with the Quarkus build graph.
 *
 * <p>The work is intentionally split across two {@link BuildStep} methods:
 *
 * <ul>
 *   <li>{@link #feature()} — a non-recording step that produces the {@link FeatureBuildItem} so the
 *       feature appears in the Quarkus startup banner. Must NOT be {@link Record @Record} — Quarkus
 *       forbids returning a build item other than {@code void} or a {@code
 *       BytecodeRecorderObjectLoader} from a recording step.
 *   <li>{@link #installChaosAgent(ChaosQuarkusRecorder)} — a {@link Record recording} step whose
 *       sole responsibility is to emit the runtime-init call into the recorder bytecode. It returns
 *       {@code void} and performs no build-item production, satisfying the recording contract.
 * </ul>
 *
 * <p>The original single-method form (returning {@link FeatureBuildItem} while annotated
 * {@code @Record(RUNTIME_INIT)}) caused {@code IllegalStateException} at build time: the deployment
 * engine tries to run the method twice — once for recording, once for the build-item output — and
 * the return-value semantics conflict with the recording proxy. Splitting removes the ambiguity.
 */
public final class ChaosQuarkusBuildStep {

  /** Default constructor; Quarkus instantiates build-step classes reflectively. */
  public ChaosQuarkusBuildStep() {}

  /**
   * Produces the feature marker for the Quarkus startup banner.
   *
   * @return a {@link FeatureBuildItem} whose name is {@code "macstab-chaos-agent"}
   */
  @BuildStep
  public FeatureBuildItem feature() {
    return new FeatureBuildItem("macstab-chaos-agent");
  }

  /**
   * Records the runtime-init call that installs the chaos agent before any application code runs.
   *
   * <p>Void return and {@code @Record(RUNTIME_INIT)}: the build step is a pure recorder with no
   * build-item output. The generated bytecode calls {@link ChaosQuarkusRecorder#installAgent()} on
   * the live recorder at application startup.
   *
   * @param recorder the build-time recorder proxy; method calls on it are recorded as bytecode
   */
  @BuildStep
  @Record(ExecutionTime.RUNTIME_INIT)
  public void installChaosAgent(final ChaosQuarkusRecorder recorder) {
    recorder.installAgent();
  }
}
